seed_everything: 42
trainer:
  callbacks:
    class_path: Metric
  logger:
    class_path: WandbLogger
    init_args:
      project: "universal-blocker"
      save_dir: "results"
  accelerator: "auto"
  devices: 1
