data:
  class_path: src.datamodules.Blocking
  init_args:
    data_dir: ./data/blocking/movies
    index_col: id
    n_neighbors: 100
    direction: forward
    batch_size: 256
    num_workers: 0
    pin_memory: false
