# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: https://github.com/asottile/pyupgrade
  rev: v2.29.1
  hooks:
  - id: pyupgrade
    args: ['--py39-plus']

- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
  - id: autoflake
    args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable', '--ignore-init-module-imports']

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort

# - repo: https://github.com/pycqa/flake8
#   rev: 4.0.1
#   hooks:
#   - id: flake8
#     additional_dependencies: [flake8-black]

- repo: https://github.com/psf/black
  rev: 21.11b1
  hooks:
  - id: black
