# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-executables-have-shebangs

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.253
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/kynan/nbstripout.git
    rev: 0.6.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.5
    hooks:
      - id: prettier
        types: [yaml]
