channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - libcxx=12.0.0
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1m
  - pip=21.2.4
  - python=3.9.7
  - readline=8.1.2
  - sqlite=3.37.2
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
      - --requirement requirements.txt
