name: blocking
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backcall=0.2.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - debugpy=1.5.1
  - decorator=5.1.0
  - entrypoints=0.3
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jupyter_client=7.0.6
  - jupyter_core=4.9.1
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - matplotlib-inline=0.1.2
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - openssl=1.1.1l
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pygments=2.10.0
  - python=3.9.7
  - python-dateutil=2.8.2
  - pyzmq=22.3.0
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - tzdata=2021e
  - wcwidth=0.2.5
  - wheel=0.37.0
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - pip:
    - --requirement requirements.txt
