seed_everything: 123
trainer:
  max_epochs: 10
  callbacks+:
    - class_path: Evaluator
    - class_path: ModelCheckpoint
      init_args:
        monitor: val/AP
        mode: max
data:
  class_path: src.datamodules.Blocking
  init_args:
    data_dir: ./data/blocking/imdb-dbpedia
    index_col: id
    n_neighbors: 100
    direction: forward
    batch_size: 64
    num_workers: 0
    pin_memory: false
