seed_everything: 123
trainer:
  max_epochs: 5
model:
  class_path: src.models.cl_encoder.CLEncoder
  init_args:
    model_name_or_path: models/bert-base-uncased
    max_length: 128
    temperature: 0.05
    learning_rate: 2.0e-05
