seed_everything: 1234
trainer:
  max_epochs: 50
  limit_val_batches: 0
  callbacks+:
    - class_path: Evaluator
model:
  class_path: src.models.DeepBlocker
  init_args:
    tokenizer: basic_english
    fasttext_model_path: ./models/wiki.en/wiki.en.bin
    aggregator_type: sif
    input_dim: 300
    hidden_dims:
      - 300
      - 150
    activations:
      class_path: torch.nn.ReLU
      init_args:
        inplace: false
    learning_rate: 0.001
