seed_everything: 123
trainer:
  max_epochs: 5
  callbacks+:
    - class_path: Evaluator
model:
  class_path: src.models.RecordFormer
  init_args:
    model_name_or_path: models/roberta-base
    max_length: 256
    augment_prob: 0.1
    hidden_dropout_prob: 0.15
    m: 0.4
    gamma: 80
    learning_rate: 2.0e-05
    distance: 0.8
    adam_epsilon: 1.0e-08
    warmup_steps: 0
    weight_decay: 0.0
    scheduler_type: linear
