seed_everything: 123
trainer:
  max_epochs: 10
  callbacks+:
    - class_path: Evaluator
model:
  class_path: src.models.RetroMAE
  init_args:
    model_name_or_path: roberta-base
    max_length: 256
    encoder_mlm_probability: 0.15
    decoder_mlm_probability: 0.3
    learning_rate: 2.0e-05
    adam_epsilon: 1.0e-08
    warmup_steps: 0
    weight_decay: 0.0
    scheduler_type: linear
