name: clencoder_fodors-zagats
seed_everything: 123
trainer:
  max_epochs: 5
model:
  class_path: src.models.simcse.SimCSE
  init_args:
    model_name_or_path: models/bert-base-uncased
    max_length: 128
    temperature: 0.05
    learning_rate: 2.0e-05
    adam_epsilon: 1.0e-08
    warmup_steps: 0
    weight_decay: 0.0
data:
  class_path: src.datamodules.matching.Matching
  init_args:
    data_dir: ./data/deepmatcher/
    dataset: Structured/Fodors-Zagats
    table_files:
      - tableA.csv
      - tableB.csv
    label_files:
      - train.csv
      - valid.csv
      - test.csv
    label_columns:
      - ltable_id
      - rtable_id
    batch_size: 64
    num_workers: 0
    pin_memory: true
