seed_everything: 123
trainer:
  max_epochs: 10
  callbacks+:
    - class_path: Evaluator
    - class_path: ModelCheckpoint
      init_args:
        monitor: val/AP
        filename: step={step}-AP={val/AP:.5f}
        auto_insert_metric_name: false
        mode: max
model:
  class_path: src.models.SimCLR
  init_args:
    model_name_or_path: models/roberta-base
    max_length: 256
    temperature: 0.05
    learning_rate: 2.0e-05
    adam_epsilon: 1.0e-08
    warmup_steps: 0
    weight_decay: 0.0
    scheduler_type: linear
