seed_everything: 123
trainer:
  max_epochs: 5
  callbacks+:
    - class_path: Evaluator
model:
  class_path: src.models.SimCLR
  init_args:
    model_name_or_path: roberta-base
    max_length: 256
    hidden_dropout_prob: 0.15
    hidden_dim: 2048
    output_dim: 4096
    temperature: 0.01
    learning_rate: 2.0e-05
    adam_epsilon: 1.0e-08
    warmup_steps: 0
    weight_decay: 0.0
    scheduler_type: linear
