name: simcse/imdb-dbpedia
seed_everything: 123
trainer:
  max_epochs: 10
  callbacks+:
    - class_path: Evaluator
    - class_path: ModelCheckpoint
      init_args:
        monitor: val/AP
        mode: max
model:
  class_path: src.models.SimCSE
  init_args:
    model_name_or_path: models/roberta-base
    max_length: 128
    temperature: 0.05
    learning_rate: 2.0e-05
    adam_epsilon: 1.0e-08
    warmup_steps: 0
    weight_decay: 0.0
    scheduler_type: linear
data:
  class_path: src.datamodules.Blocking
  init_args:
    data_dir: ./data/blocking/imdb-dbpedia
    index_col: id
    n_neighbors: 100
    direction: forward
    batch_size: 64
    num_workers: 0
    pin_memory: false
