name: simcse/gittables
seed_everything: 123
trainer:
  max_epochs: 1
  max_steps: 10000
  check_val_every_n_epoch: null
  val_check_interval: 100
  callbacks+:
    - class_path: Metric
    - class_path: Evaluator
    - class_path: OnlineEvaluator
      init_args:
        data_dir: "data/blocking/walmart-amazon_homo"
    - class_path: ModelCheckpoint
      init_args:
        monitor: "val/AP"
        filename: "step={step}-AP={val/AP:.5f}"
        auto_insert_metric_name: false
        mode: max
        save_top_k: 5
model:
  class_path: src.models.SimSiam
  init_args:
    model_name_or_path: models/roberta-base
    max_length: 256
    temperature: 0.05
    learning_rate: 2.0e-05
    adam_epsilon: 1.0e-08
    warmup_steps: 0
    weight_decay: 0.0
    scheduler_type: linear
data:
  class_path: src.datamodules.GitTables
  init_args:
    data_dir: ./data/gittables/processed/
    data_files: null
    batch_size: 128
    num_workers: 0
    pin_memory: true
