seed_everything: 123
trainer:
  max_epochs: 5
  callbacks+:
    - class_path: Evaluator
model:
  class_path: src.models.Sudowoodo
  init_args:
    model_name_or_path: models/distilbert-base-uncased
    max_length: 256
    augment_prob: 1.0
    hidden_dropout_prob: 0.10
    hidden_dim: 2048
    output_dim: 4096
    temperature: 0.07
    alpha: 0.5
    lambd: 0.0039
    learning_rate: 5.0e-05
    adam_epsilon: 1.0e-08
    warmup_steps: 0
    weight_decay: 0.0
    scheduler_type: linear
